"""empty message

Revision ID: 195d604305dc
Revises: 
Create Date: 2022-06-23 18:53:33.366459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195d604305dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_genres_book_id_books')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_book_genres_genre_id_genres')),
    sa.PrimaryKeyConstraint('id', 'book_id', 'genre_id', name=op.f('pk_book_genres'))
    )
    op.drop_constraint('fk_covers_book_id_books', 'covers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_covers_book_id_books'), 'covers', 'books', ['book_id'], ['id'])
    op.drop_constraint('fk_reviews_user_id_users', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_book_id_books', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_book_id_books'), 'reviews', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_book_id_books'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_book_id_books', 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_reviews_user_id_users', 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_covers_book_id_books'), 'covers', type_='foreignkey')
    op.create_foreign_key('fk_covers_book_id_books', 'covers', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_table('book_genres')
    # ### end Alembic commands ###
